name: Call Firebase Function Every 1 Minute

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every 10 minutes

jobs:
  call-firebase-function:
    runs-on: ubuntu-latest

    steps:
      - name: Call Firebase Function
        run: |
          curl -X POST "${{ secrets.SERVERLESS_FUNCTION_URL }}" \
            -H "Content-Type: application/json" \
            -d '{
              "message": "GitHub Action Triggered",
              "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
            }'
