name: Call Firebase Function Every Minute

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every minute
  workflow_dispatch:  # Allows manual triggering

jobs:
  call-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Firebase Function
        run: curl -X POST https://us-central1-delforms.cloudfunctions.net/testEventLogger
